### ISSUE TITLE
Publically accessable Song Queue

### ISSUE THREAD

**Issue by Magentah** [Magentah/chewie-bot#16]
A publically accessable version of the Song Requests UI that can be viewed without logging in, or when logging in with a normal user.

- Can view songs in queue.
- If logged in, can see where your request is, if you have one
- Can request through the UI if logged in and requests are available.

**Comment by floele** [comment]
@Magentah Is this the general idea you had in mind?
https://github.com/floele/chewie-bot/commit/0e120c24c446e54152e078fe2e51ccdb19286460

UI would look like this if you only have viewer permissions.
![grafik](https://user-images.githubusercontent.com/906319/103139645-8ac85180-46de-11eb-8e20-5198e5dabd5a.png)

If so, I can continue with that.

**Comment by Magentah** [comment]
@floele Yeah that's pretty much what I was thinking. Not entirely sure what would be on the Home page - maybe their own own details like VIP status, subscription status, how many points they have? That's another issue though.
