### ISSUE TITLE
Implement quotes system

### ISSUE THREAD

**Issue by floele** [Magentah/chewie-bot#51]
Implement command for adding quotes (limited to mods):
`!addquote <name> <quote>` (name is the person who said it)

Implement command for posting a quote:
`!quote <number>`
`!quote [search]` (optional search argument to search for quotes with a specific content, otherwise random quote)

Quotes need to be saved to a separate database table with columns (id, text, author, dateAdded, addedByUserName)

**Comment by ghokane** [comment]
@Magentah this one
