### ISSUE TITLE
Implement !sudoku command

### ISSUE THREAD

**Issue by floele** [Magentah/chewie-bot#52]
Time out users for 120 seconds if either
-  the !sudoku command
-  or the "chewieSudoku" emote is used 
-  or "sudoku" is used in a message

Does not apply to mods.
Output message: `<user> just got their guts spilled chewieSudoku`

**Comment by Magentah** [comment]
This can be done using `this.client.timeout()` in `TwitchService`. Check existing commands for how to use the twitch service in a command.
