### ISSUE TITLE
Implement !redeem commands

### ISSUE THREAD

**Issue by floele** [Magentah/chewie-bot#55]
The following commands need to be implemented:

- !redeemclap
- !redeemcatjam
- !redeemcomfy

Each of those commands to the following:

1. Deduct 500 points
2. Post a row of emotes in chat (Clap, CatJAM, chewieMmm)
3. Make a GIF (which contains the animation) appear on a website which is used as "browser source" in SLOBS

All animations have a shared cooldown (length of the animation) so that they do not overlap. The cooldown should also be shared with animations invoked by donating bits. It might also be worth considering to queue animations so that nothing gets dropped.

Details regarding 3)
This is currently implemented by a separate Deepbot website that shows the animation, like this:
http://deepbot.tv/widgets/ImagePanel.htm?dur=5&test=0&panel=redeemclap&w=1280&h=720
Dynamic update of the page probably needs use of websockets or something similar.

It might be easier to use the Streamlabs API and post alerts though (https://dev.streamlabs.com/docs/triggering-alerts, https://stream-labs.github.io/streamlabs-obs-api-docs/docs/index.html#request). Requires #23 

Needs some evaluation which method is better.

**Comment by Magentah** [comment]
I think if possible, we should use the streamlabs alert api to post alerts instead of how deepbot does it. Creating new site pages for alerts that need to be used in browser source sounds like an awful way to handle it.
