### ISSUE TITLE
Streamlabs:  Handle Streamlabs Donations and Subscriptions

### ISSUE THREAD

**Issue by Magentah** [Magentah/chewie-bot#73]
When a user makes a donation through Streamlabs, their profile data should be updated in the bot.

- Configuration settings should be available for the following:
  - Give points for donation, with multiplier option.
  - Give VIP status for donation, with configurable minimum amounts for each VIP level
  - Give points for subscribing, with multiplier option
  - Give VIP status for subscribing, configurable based on subscription tier.
- When we receive an event, check if it should update the user
- If it should, use configured options to update user.
- Save donations to database

In addition to user status, we want to parse the message from donations and subscriptions for song requests:

- Enable/Disable platforms (Spotify, Youtube, etc).
  - Enabled platforms should have necessary configuration and be able to successfully authenticate with said platform.
- Configure which events are able to request songs.
  - Donations should have a configurable minimum amount for requests to be parsed.
  - Subscriptions should have an option to configure which subscription tier is required to parse requests.
- When receiving an event, check the configured values.
- If enabled, parse message text for platform link urls
- Receive data from platform
- Add data to Song Request Queue.

**Comment by floele** [comment]
Points to give for events:
Gifted Sub: 500 Chews
Donation: 100 chews per dollar
Cheer: 100 chews per 100 bits
