### ISSUE TITLE
Show VIP status history for user (own profile) and broascaster (all users)

### ISSUE THREAD

**Issue by Magentah** [Magentah/chewie-bot#82]
There should be logs saved any time the VIP status for a user changes, with the reason it changed (donation, subscription, expiry, etc).

These logs should be viewable by the broadcaster and (optionally) mods.
Users should be able to see their own VIP status history.

**Comment by floele** [comment]
Logging is done. UI needs to be added in the bot though to view a user's history. That's why I consider this a good first issue.
